controllers:
    resource: ../src/Controller/
    type: attribute

# config/routes.yaml
app_homepage:
  path: /
  controller: App\Controller\AccountController::index

account_delete:
  path: '/account/{id}'
  controller: App\Controller\AccountController::delete
  methods: [POST]